[[plugins]]
repo = 'mattn/webapi-vim'
on_cmd  = ['HatebloCreate']

[[plugins]]
repo = 'racer-rust/vim-racer'
on_ft = 'rust'
hook_source = '''
    let g:racer_cmd = '/home/'.$USER.'/.cargo/bin/racer'
    let $RUST_SRC_PATH=systemlist('rustc --print sysroot')[0].'/lib/rustlib/src/rust/src'
'''

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_source = '''
    let g:rustfmt_autosave = 0
    let g:rust_doc#define_map_K = 0
    autocmd FileType rust nnoremap <Leader>8 :RustFmt<CR>:w<CR>
'''

# refactoring tool
[[plugins]]
on_ft = 'python'
repo = 'fx-kirin/python-mode'

[[plugins]]
on_ft = 'python'
repo = 'psf/black'

[[plugins]]
on_ft = 'python'
repo = 'lambdalisue/vim-pyenv'

[[plugins]]
on_ft = 'csv'
repo = 'chrisbra/csv.vim'
