[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_source = '''
    let g:rustfmt_autosave = 0
    let g:rust_doc#define_map_K = 0
    autocmd FileType rust nnoremap <Leader>o :RustFmt<CR>:w<CR>
'''

[[plugins]]
on_ft = 'python'
repo = 'psf/black'

[[plugins]]
on_ft = 'python'
repo = 'lambdalisue/vim-pyenv'

[[plugins]]
on_ft = 'csv'
repo = 'chrisbra/csv.vim'

[[plugins]]
on_ft = 'markdown'
repo = 'godlygeek/tabular'

[[plugins]]
on_ft = 'markdown'
depends = ['tabular']
repo = 'plasticboy/vim-markdown'

[[plugins]]
on_ft = 'python'
repo = 'mfussenegger/nvim-dap-python'
hook_source = '''
lua require('dap-python').setup('/home/zenbook/.pyenv/versions/3.8.3/bin/python')
'''
