[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_source = '''
    let g:rustfmt_autosave = 0
    let g:rust_doc#define_map_K = 0
    autocmd FileType rust nnoremap <Leader>o :RustFmt<CR>:w<CR>
'''

# refactoring tool
[[plugins]]
on_ft = 'python'
repo = 'fx-kirin/python-mode'

[[plugins]]
on_ft = 'python'
repo = 'psf/black'

[[plugins]]
on_ft = 'python'
repo = 'lambdalisue/vim-pyenv'

[[plugins]]
on_ft = 'csv'
repo = 'chrisbra/csv.vim'

[[plugins]]
repo = 'racer-rust/vim-racer'
on_ft = 'rust'
hook_source = '''
    let g:racer_cmd = '/home/'.$USER.'/.cargo/bin/racer'
    let $RUST_SRC_PATH=systemlist('rustc --print sysroot')[0].'/lib/rustlib/src/rust/src'
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
merged = 0
hook_add = '''
let g:deoplete#enable_at_startup = 1
inoremap <silent><expr> <C-n>  pumvisible() ? "\<C-n>" : deoplete#manual_complete()
'''
hook_post_source = '''
call deoplete#custom#option({
\ 'ignore_case': v:true,
\ 'smart_case': v:true,
\ 'on_insert_enter': v:false,
\ 'camel_case': v:true,
\ 'profile': v:true,
\})
'''

[[plugins]]
repo = 'sebastianmarkow/deoplete-rust'
on_ft = 'rust'
on_i = 1
depends = ['deoplete.nvim']
merged = 0
hook_source = '''
    let g:deoplete#sources#rust#racer_binary=systemlist('which racer')[0]
    let g:deoplete#sources#rust#rust_source_path=systemlist('rustc --print sysroot')[0].'/lib/rustlib/src/rust/src'
    let $RUST_SRC_PATH=systemlist('rustc --print sysroot')[0].'/lib/rustlib/src/rust/src'
    let g:deoplete#sources#rust#show_duplicates=1
    let g:deoplete#sources#rust#disable_keymap=1
    nmap <buffer> gd <plug>DeopleteRustGoToDefinitionDefault
    nmap <buffer> K  <plug>DeopleteRustShowDocumentation
'''

[[plugins]]
repo = 'Shougo/neco-vim'
merged = 0
on_ft = ['vim']
on_i = 1
depends = ['deoplete.nvim']

[[plugins]]
repo = 'deoplete-plugins/deoplete-jedi'
merged = 0
on_ft = 'python'
depends = ['deoplete.nvim']
on_i = 1
hook_add = '''
let g:deoplete#sources#jedi#python_path = $HOME.'/.pyenv/versions/3.8.3/bin/python'
let g:deoplete#sources#jedi#show_docstring = 1
'''

[[plugins]]
repo = 'Shougo/echodoc.vim'
depends = ['deoplete.nvim']
